CacheDriver = "file" ## or redis
CachePath = "/var/lib/t2m_cache"
SkipReply = true
TwitterKey = ""
TwitterSecretKey = ""
TwitterToken =  ""
TwitterTokenSecret  = ""
TwitterScreenName  = ""

[[Mastodons]]
Enable  =  true
Server  = ""
ClientID  = ""
ClientSecret = ""
Token   = ""

[[Redis]]
Host  = "reds"
Port  = 6379
Password = ""
DB  = 0